USE FilmShop;

CREATE TABLE Catalogue (
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Catalogue PRIMARY KEY,

	CatalogueU VARCHAR(255) NOT NULL,

	ID_Film UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_CatalogueFilm FOREIGN KEY 
	REFERENCES Film(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	Price INT NOT NULL,
	[Status] BIT NOT NULL,

	ID_StorageMedium UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_CatalogueStorageMedium FOREIGN KEY 
	REFERENCES StorageMedium(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);

ALTER TABLE Catalogue
ADD CONSTRAINT u_CatalogueCatalogueU UNIQUE([CatalogueU]);