USE FilmShop;

CREATE TABLE Purchase (
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Purchase PRIMARY KEY,
	PurchaseU VARCHAR(255) NOT NULL,
	PurchaseDate DATE NOT NULL,
	CreditCard VARCHAR(255) NOT NULL,
	TelephoneNumber VARCHAR(255) NOT NULL,
);

ALTER TABLE Purchase
ADD CONSTRAINT u_PurchasePurchaseU UNIQUE(PurchaseU);