USE FilmShop;

CREATE TABLE Country (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Country PRIMARY KEY,
    [Name] VARCHAR(255) NOT NULL,
);

ALTER TABLE Country
ADD CONSTRAINT u_CountryName UNIQUE([Name]);