USE FilmShop;

CREATE TABLE Film (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Film PRIMARY KEY,
    [Name] VARCHAR(255) NOT NULL,
	[Description] VARCHAR(255) NOT NULL,
	Duration INT NOT NULL,

	ID_Country UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_FilmCountry FOREIGN KEY 
	REFERENCES Country(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_Genre UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_FilmGenre FOREIGN KEY 
	REFERENCES Genre(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_Director UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_FilmDirector FOREIGN KEY 
	REFERENCES Director(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);