USE FilmShop;

CREATE TABLE Director (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Director PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
    Birthdate DATE NOT NULL,
	Deathdate DATE DEFAULT NULL,
);