USE FilmShop;

CREATE TABLE Actor (
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Actor PRIMARY KEY,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Birthdate DATE NOT NULL,
	Deatdate DATE DEFAULT NULL,
);