USE FilmShop;

CREATE TABLE Genre (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Genre PRIMARY KEY,
    [Name] VARCHAR(255) NOT NULL,
);

ALTER TABLE Genre
ADD CONSTRAINT u_GenreName UNIQUE([Name]);