CREATE FUNCTION dbo.fFilmID
(
	@FilmName VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Genre UNIQUEIDENTIFIER = (SELECT TOP 1 ID FROM Film WHERE [Name] = @FilmName);
	RETURN @ID_Genre;
END;